-- El catalogo de rubros. Se agregan filas, no codigo.
-- precio_ref_min y precio_ref_max son el rango de referencia que se muestra mientras la categoria
-- todavia no tiene solicitudes de las que sacar precios reales.
create table categoria (
    id_categoria    bigint generated by default as identity primary key,
    nombre          varchar(60)    not null,
    descripcion     varchar(200),
    icono           varchar(40),
    precio_ref_min  numeric(10, 2) not null,
    precio_ref_max  numeric(10, 2) not null,
    estado          varchar(20)    not null default 'ACTIVA',
    constraint uk_categoria_nombre unique (nombre),
    constraint ck_categoria_estado check (estado in ('ACTIVA', 'INACTIVA')),
    constraint ck_categoria_precios check (precio_ref_min > 0 and precio_ref_max >= precio_ref_min)
);

-- las mismas ocho de datos/categorias.json, con los mismos ids, para que las pantallas que todavia
-- leen el json y la base no se contradigan
insert into categoria (id_categoria, nombre, icono, precio_ref_min, precio_ref_max) values
    (1, 'Música',               'bi-music-note-beamed',  50,  120),
    (2, 'Hogar y reparaciones', 'bi-tools',              60,  450),
    (3, 'Idiomas',              'bi-translate',          40,   90),
    (4, 'Diseño',               'bi-palette',            80,  400),
    (5, 'Tecnología',           'bi-cpu',                70,  350),
    (6, 'Clases escolares',     'bi-book',               30,   80),
    (7, 'Belleza',              'bi-scissors',           25,  150),
    (8, 'Mascotas',             'bi-heart',              20,  100);

-- los ids se insertaron a mano, asi que el contador arranca despues del ultimo
alter table categoria alter column id_categoria restart with 9;

-- la declaracion de habilidades ya puede apuntar al catalogo
alter table perfil_categoria
    add constraint fk_perfil_categoria_categoria
    foreign key (id_categoria) references categoria (id_categoria);
