-- Las cinco tablas del flujo del negocio, en el orden en que se pueden crear sin romper las
-- claves foraneas.

-- lo que alguien necesita y cuanto propone pagar.
-- id_destinatario vacio: la ve todo el mundo. con valor: es una propuesta directa a esa persona.
create table solicitud (
    id_solicitud       bigint generated by default as identity primary key,
    id_categoria       bigint         not null,
    id_destinatario    bigint,
    id_autor           bigint         not null,
    titulo             varchar(120)   not null,
    descripcion        varchar(1000)  not null,
    modalidad          varchar(20)    not null,
    distrito           varchar(60),
    latitud            numeric(9, 6),
    longitud           numeric(9, 6),
    fecha_deseada      date,
    precio_propuesto   numeric(10, 2) not null,
    estado             varchar(20)    not null default 'ABIERTA',
    fecha_publicacion  timestamp      not null default current_timestamp,
    constraint fk_solicitud_categoria foreign key (id_categoria) references categoria (id_categoria),
    constraint fk_solicitud_destinatario foreign key (id_destinatario) references usuario (id_usuario),
    constraint fk_solicitud_autor foreign key (id_autor) references usuario (id_usuario),
    constraint ck_solicitud_modalidad check (modalidad in ('PRESENCIAL', 'VIRTUAL')),
    constraint ck_solicitud_estado check (estado in ('ABIERTA', 'EN_CURSO', 'CERRADA', 'CANCELADA')),
    constraint ck_solicitud_precio check (precio_propuesto > 0),
    constraint ck_solicitud_destinatario check (id_destinatario is null or id_destinatario <> id_autor)
);

-- la respuesta de quien sabe hacerlo, con el precio pedido u otro.
-- una persona hace una sola oferta por solicitud.
create table oferta (
    id_oferta        bigint generated by default as identity primary key,
    id_solicitud     bigint         not null,
    id_usuario       bigint         not null,
    monto_propuesto  numeric(10, 2) not null,
    mensaje          varchar(500),
    estado           varchar(20)    not null default 'ENVIADA',
    fecha_oferta     timestamp      not null default current_timestamp,
    constraint uk_oferta_solicitud_usuario unique (id_solicitud, id_usuario),
    constraint fk_oferta_solicitud foreign key (id_solicitud) references solicitud (id_solicitud),
    constraint fk_oferta_usuario foreign key (id_usuario) references usuario (id_usuario),
    constraint ck_oferta_estado check (estado in ('ENVIADA', 'ACEPTADA', 'RECHAZADA')),
    constraint ck_oferta_monto check (monto_propuesto > 0)
);

-- nace cuando se acepta una oferta. guarda el monto final y la comision que se calculo entonces.
create table servicio (
    id_servicio   bigint generated by default as identity primary key,
    id_oferta     bigint         not null,
    monto_final   numeric(10, 2) not null,
    comision      numeric(10, 2) not null,
    fecha_inicio  timestamp      not null default current_timestamp,
    fecha_cierre  timestamp,
    estado        varchar(20)    not null default 'EN_CURSO',
    constraint uk_servicio_oferta unique (id_oferta),
    constraint fk_servicio_oferta foreign key (id_oferta) references oferta (id_oferta),
    constraint ck_servicio_estado check (estado in ('EN_CURSO', 'CERRADO')),
    constraint ck_servicio_montos check (monto_final > 0 and comision >= 0),
    constraint ck_servicio_fechas check (fecha_cierre is null or fecha_cierre >= fecha_inicio)
);

-- la conversacion de cada oferta
create table mensaje (
    id_mensaje   bigint generated by default as identity primary key,
    id_oferta    bigint        not null,
    id_emisor    bigint        not null,
    contenido    varchar(1000) not null,
    fecha_envio  timestamp     not null default current_timestamp,
    leido        boolean       not null default false,
    constraint fk_mensaje_oferta foreign key (id_oferta) references oferta (id_oferta),
    constraint fk_mensaje_emisor foreign key (id_emisor) references usuario (id_usuario),
    constraint ck_mensaje_contenido check (length(trim(contenido)) > 0)
);

-- cada parte califica a la otra una sola vez por servicio, asi que un servicio tiene dos como maximo
create table calificacion (
    id_calificacion  bigint generated by default as identity primary key,
    id_servicio      bigint       not null,
    id_evaluador     bigint       not null,
    id_evaluado      bigint       not null,
    puntaje          smallint     not null,
    comentario       varchar(500),
    fecha            timestamp    not null default current_timestamp,
    constraint uk_calificacion_servicio_evaluador unique (id_servicio, id_evaluador),
    constraint fk_calificacion_servicio foreign key (id_servicio) references servicio (id_servicio),
    constraint fk_calificacion_evaluador foreign key (id_evaluador) references usuario (id_usuario),
    constraint fk_calificacion_evaluado foreign key (id_evaluado) references usuario (id_usuario),
    constraint ck_calificacion_puntaje check (puntaje between 1 and 5),
    constraint ck_calificacion_partes check (id_evaluador <> id_evaluado)
);
