create table usuario (
    id_usuario     bigint generated by default as identity primary key,
    nombre         varchar(80)  not null,
    apellidos      varchar(80)  not null,
    email          varchar(120) not null,
    password_hash  varchar(100) not null,
    telefono       varchar(20),
    tipo_perfil    varchar(20)  not null,
    fecha_registro timestamp    not null,
    estado         varchar(20)  not null,
    constraint uk_usuario_email unique (email),
    constraint ck_usuario_tipo_perfil check (tipo_perfil in ('CLIENTE', 'EXPERTO', 'ADMIN')),
    constraint ck_usuario_estado check (estado in ('ACTIVO', 'SUSPENDIDO'))
);

create table perfil_experto (
    id_perfil      bigint generated by default as identity primary key,
    id_usuario     bigint not null,
    descripcion    varchar(500),
    experiencia    varchar(500),
    calif_promedio numeric(3, 2) not null default 0,
    constraint uk_perfil_experto_usuario unique (id_usuario),
    constraint fk_perfil_experto_usuario foreign key (id_usuario) references usuario (id_usuario)
);
