create table perfil_categoria (
    id_perfil_categoria bigint generated by default as identity primary key,
    id_perfil           bigint not null,
    id_categoria        bigint not null,
    constraint uk_perfil_categoria unique (id_perfil, id_categoria),
    constraint fk_perfil_categoria_perfil foreign key (id_perfil) references perfil_experto (id_perfil)
);
